# Generated by Django 4.1.1 on 2023-05-07 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saloonistapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=90)),
                ('phone', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=25)),
                ('passwd', models.CharField(max_length=25)),
            ],
        ),
        migrations.RemoveField(
            model_name='salon',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.DeleteModel(
            name='Salon',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
