# Generated by Django 4.1.1 on 2023-05-07 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saloonistapp', '0002_userdetails_remove_salon_created_by_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserDetails',
            new_name='UserDetail',
        ),
    ]
