# Generated by Django 4.1.1 on 2023-05-07 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saloonistapp', '0005_booking_delete_bookings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
